### ISSUE TITLE
There is a typo in red-queue-disc-test-suite

### ISSUE THREAD

**Issue by mohittahiliani** [phanikiran2/Extending-RED-qdisc-in-ns3-to-support--NLRED#1]
See the comment [here](https://github.com/phanikiran2/Extending-RED-qdisc-in-ns3-to-support--NLRED/commit/b4a48ceaa0908566fd282fa511acf5e91ce00de8#commitcomment-19595194)

and remove the typo

**Comment by mohittahiliani** [comment]
@phanikiran2 - I'm telling about Line #308, which looks like

Verify that we can actually set the attribute NonLinear

In that line, it should be "Gentle" instead of "NonLinear"

**Comment by nichit93** [comment]
Sir i committed the change a few minutes ago.

**Comment by phanikiran2** [comment]
Dear sir,
Issue resolved.

Regards
PhaniKiran &Nichit
